add CI
rg3dengine/rusty-editor pull request #23
Opened 2021-05-25 20:17 UTC by Voodlaz

This PR adds CI and #19 closes . The CI currently checks and tests the codebase.

Checking it via cargo check essentially makes sure the code will compile without actually compiling it. It still takes a bit to run (10 mins), but that's mainly due to the fact that it's not using incremental compilation and the library is quite large.

Please don't merge this until the tests on my branch have passed.

2021-05-25 20:19 UTC, Voodlaz commented
Now for the wasm

2021-05-26 11:05 UTC, mrDIMAS requested changes

2021-05-26 11:05 UTC, mrDIMAS commented on README.md
> +[![CI Status](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml/badge.svg)](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml)
Please do not remove this line, it is better to fix URL to `https://github.com/rg3dengine/rg3d`. Also I think new URLs are invalid, they should be `https://github.com/rg3dengine/rusty-editor/actions/workflows/ci.yml/badge.svg` and `https://github.com/rg3dengine/rusty-editor/actions/workflows/ci.yml`.

2021-05-26 11:17 UTC, Voodlaz commented on README.md
> +[![CI Status](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml/badge.svg)](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml)
Whoops

2021-05-26 11:17 UTC, Voodlaz commented on README.md
> +[![CI Status](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml/badge.svg)](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml)
I accidentally removed the line

2021-05-26 11:22 UTC, Voodlaz commented on README.md
> +[![CI Status](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml/badge.svg)](https://github.com/gideongrinberg/rusty-editor/actions/workflows/ci.yml)
Okay I fixed it

2021-05-26 18:35 UTC, mrDIMAS commented
Ok, now it _looks good_, merging. Thanks!

2021-05-26 18:35 UTC, merged