.deb and general linux support
rg3dengine/rusty-editor pull request #34
Opened 2021-06-15 20:51 UTC by Voodlaz

This PR will add package data for cargo-deb util to create an installable deb package, and general linux and crossplatfrom support(crossplatfrom have some not done yet parts). This includes sections in deb packages, crossplatfrom config and data directories putting assets in the right place. This partly solve this issue: #24

2021-06-17 20:24 UTC, Voodlaz commented
we'll still need a normal icon..

2021-06-18 12:43 UTC, Voodlaz commented
I made the icon, now it's good to go.

2021-06-18 14:03 UTC, Voodlaz commented
oh dear, I forgot about dependencies.

2021-06-20 17:41 UTC, Voodlaz commented
I added rpm

2021-06-21 11:34 UTC, Voodlaz commented
@mrDIMAS , okay, I think I;ve done everything.

2021-06-23 17:45 UTC, mrDIMAS commented
In general it looks fine, but I please run `clippy` to make code more idiomatic - for example you have `return` statements at the end of functions, checking boolean statements with `== true` or `== false` which is not wrong, but a bit useless, and some more tiny issues. 

Also, why do you need to change path to resources? Maybe it is worth to just use `include_bytes!` macro to embed resources in the final binary?

2021-06-23 18:15 UTC, Voodlaz commented
@mrDIMAS 

- ran clippy suggestions
- about that. existence resources is an easy way to check whetter the programm is installed or not.

2021-06-23 19:46 UTC, Voodlaz commented
> Also, why do you need to change path to resources? Maybe it is worth to just use `include_bytes!` macro to embed resources in the final binary?

Wouldn't it be more neat to use resources inside resources folder that standarts make?

2021-06-25 22:00 UTC, mrDIMAS requested changes
Please fix the commented lines.

2021-06-26 09:34 UTC, Voodlaz commented on src/custom_dirs.rs
> +pub fn resources_dir(category: &str, filename: &str) -> PathBuf {
great! I see you embeded that font into the binary!

2021-06-26 09:34 UTC, Voodlaz commented on src/custom_dirs.rs
> +pub fn resources_dir(category: &str, filename: &str) -> PathBuf {
will remove it.

2021-06-26 09:35 UTC, Voodlaz commented on src/custom_dirs.rs
> +        let startup_working_dir = debug_dir(filename);
okay

2021-06-26 09:35 UTC, Voodlaz commented on src/custom_dirs.rs
> +        let startup_working_dir = debug_dir(filename);
okay

2021-06-26 09:35 UTC, Voodlaz commented on src/custom_dirs.rs
> +        let project_dir = ProjectDirs::from("org","rg3dengine", "rusty-editor");
okay

2021-06-26 09:36 UTC, Voodlaz commented on src/custom_dirs.rs
> +        let project_dir = ProjectDirs::from("org","rg3dengine", "rusty-editor");
okay

2021-06-26 09:36 UTC, Voodlaz commented on src/main.rs
> +            if test {
okay

2021-06-26 09:36 UTC, Voodlaz commented on src/custom_dirs.rs
> +    let project_dir = ProjectDirs::from("org","rg3dengine", "rusty-editor");
okay

2021-06-26 09:36 UTC, Voodlaz commented on src/custom_dirs.rs
> +    let dirs = std::env::current_dir().unwrap();
okay

2021-06-26 09:36 UTC, Voodlaz commented on src/custom_dirs.rs
> +pub fn config_dir_test(filename: &str) -> PathBuf {
okay

2021-06-26 09:37 UTC, Voodlaz commented
whoops, accidently pressed reviewer needed button

2021-06-28 09:38 UTC, mrDIMAS requested changes
Please run `cargo fmt` to unify code formatting. Also use a spell checker, there's lots of grammatical errors in comments.

2021-06-28 09:38 UTC, mrDIMAS commented on src/custom_dirs.rs
> +pub fn resources_dir_test(filename: &str) -> PathBuf {
Remove this function, it is not used anyway.

2021-06-28 16:34 UTC, mrDIMAS requested changes
Please fix typos and then I'll merge the PR.

2021-06-28 16:34 UTC, mrDIMAS commented on os-installation/general-description.txt
> +rg3d is a feature rich game egine made in rust, which allows
typo `egine`

2021-06-28 16:34 UTC, mrDIMAS commented on os-installation/general-description.txt
> +you to build shooters, platfomers, sandoxes and more
typo `sandoxes`

2021-06-28 16:34 UTC, mrDIMAS commented on resources/README.md
> +- embed - for stuff like icons and fonts that are embeded into binary
typo `embeded`

2021-06-28 16:34 UTC, mrDIMAS commented on resources/README.md
> +- lib - for other stuff that couldn't be embeded into binary, but have to be used rust code like embadble icons.
typos `embeded` and `embadble`

2021-06-28 16:34 UTC, mrDIMAS commented on resources/README.md
> +- etc - for everything that dosen't fit into this categories. for example, icons for system launchpad.
typo `dosen't`

2021-06-28 16:34 UTC, mrDIMAS commented on resources/lib/release.toml
> +# Do not switch the switch inside cargo project, it's usefull
typo `usefull`

2021-06-28 16:34 UTC, mrDIMAS commented on resources/lib/release.toml
> +# OS to installed programms, like ProgamFiles on windows
typo `ProgamFiles`

2021-06-28 21:07 UTC, merged