fix CTRL+L . add menu shortcuts . settings window  public
rg3dengine/rusty-editor pull request #49
Opened 2021-09-29 17:25 UTC by zhneeshnek

fix and move "load scene" shortcut to menu.rs 

add some menu shortcuts. 

make root ui node of SettingsWindow public to quickly check visibility()

2021-09-29 19:01 UTC, mrDIMAS requested changes
Hi! Thanks for the PR! I have few small requests, if you have time to fix these, that would be awesome.

2021-09-29 19:01 UTC, mrDIMAS commented on src/menu.rs
> +                match result {
This `match` block looks to be almost identical to the one below, could you please create a function to reduce code duplication?

2021-09-30 07:21 UTC, zhneeshnek commented on src/menu.rs
> +        let mut skip_shortcuts: bool = false;
yes it is unsafe tbh. tried my best but right now is a little above my head i suppose. i agree it's better to do this via message routing. will try to dig in deeper into the code base and see if i can make this improvement

2021-09-30 07:23 UTC, zhneeshnek commented on src/menu.rs
> +        let close_scene_message_box = MessageBoxBuilder::new(
ok!

2021-09-30 07:24 UTC, zhneeshnek commented on src/menu.rs
> +                match result {
ok!

2021-09-30 19:40 UTC, mrDIMAS commented on src/menu.rs
> +        let mut skip_shortcuts: bool = false;
It is actually kinda fundamental flaw of the `rg3d-ui` and I'd leave it as is in the PR.

2021-10-01 08:11 UTC, zhneeshnek commented on src/menu.rs
> +        let mut skip_shortcuts: bool = false;
https://github.com/rg3dengine/rusty-editor/pull/49/commits/dd878a25c67b9e45594f8e91dc0c94c0b81a3def

2021-10-01 08:12 UTC, zhneeshnek commented on src/menu.rs
> +        let close_scene_message_box = MessageBoxBuilder::new(
https://github.com/rg3dengine/rusty-editor/pull/49/commits/dd878a25c67b9e45594f8e91dc0c94c0b81a3def

2021-10-01 08:12 UTC, zhneeshnek commented on src/menu.rs
> +                match result {
https://github.com/rg3dengine/rusty-editor/pull/49/commits/dd878a25c67b9e45594f8e91dc0c94c0b81a3def

2021-10-01 09:20 UTC, zhneeshnek commented on src/menu.rs
> +        let mut skip_shortcuts: bool = false;
not flawed from my perspective. UserInterface::top_picking_restriction() seems to have solved it

2021-10-01 11:41 UTC, zhneeshnek reviewed
If interested please view https://github.com/rg3dengine/rusty-editor/pull/49/commits/263d90ff23b0a1b3af7080df24cc61e543c14e28

will need to remove this one. sorry. im a total git/github noob.

2021-10-01 17:14 UTC, mrDIMAS requested changes

2021-10-01 17:14 UTC, mrDIMAS commented on .gitignore
> +*.toml
Why?

2021-10-01 17:14 UTC, mrDIMAS commented on Cargo.toml
> +rg3d = { path = "../../rg3d" }
Why?

2021-10-01 17:14 UTC, mrDIMAS commented on src/menu.rs
> +fn make_new_scene_message_box(ctx: &mut BuildContext) -> Handle<UiNode> {
Three following functions are almost identical, except the text in `.with_text(...)`. Please create _one_ function with parameter and use it, instead of three functions.

2021-10-01 17:14 UTC, mrDIMAS commented on src/menu.rs
> +                                    //    .send(Message::SaveAndLoadScene(path.to_owned(), editor_scene.load_path.as_ref().unwrap().to_path_buf()))
remove

2021-10-01 17:14 UTC, mrDIMAS commented on src/menu.rs
> +                                    /*
remove

2021-10-01 17:14 UTC, mrDIMAS commented on src/menu.rs
> +                                    /*
remove

2021-10-02 12:36 UTC, zhneeshnek commented on Cargo.toml
> +rg3d = { path = "../../rg3d" }
im noob xD sry

2021-10-04 18:37 UTC, closed without merging